config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  root 'static_pages#home'
end

app/models/rails_flavoured_ruby.rb
class Word
  def palindrome?(string)
    string == string.reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')         # method definition and optional argument
    base_title = "Word Machine Blog"      # variable assignment
    if page_title.empty?                  # boolean test
      base_title                          # implicit return
    else
      page_title + " | " + base_title     # string concatenation
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:page_title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
</head>
  <body>
    <br />
    <div class="btn-group">
      <%= link_to 'Home', static_pages_home_path, class: 'btn btn-primary' %>
      <%= link_to 'Help', static_pages_help_path, class: 'btn btn-primary' %>
      <%= link_to 'About', static_pages_about_path, class: 'btn btn-primary' %>
      <%= link_to 'Contact', static_pages_contact_path, class: 'btn btn-primary' %>
    </div>
    <br />
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:page_title, "About") %>

<h1>Word Machine About</h1>
<p>
  This is the link to the <%= link_to("http://www.worldmachine.ie/#my-about-form", target: '_blank') do %>World Machine
  <% end %> about page.
</p>

app/views/static_pages/contact.html.erb
<% provide(:page_title, "Contact") %>

<h1>Word Machine Contact</h1>
<p>
  This is the link to the <%= link_to("http://www.worldmachine.ie/#my-contact-form", target: '_blank') do %>World Machine
  <% end %> contact page.
</p>

app/views/static_pages/help.html.erb
<% provide(:page_title, "Help") %>

<h1>Word Machine Help</h1>
<p>
  This is the link to the <%= link_to("http://www.worldmachine.ie/#my-portfolio-form", target: '_blank') do %>World Machine
  <% end %> help page.
</p>

app/views/static_pages/home.html.erb
<h1>Word Machine Home</h1>
<p>
  This is the link to the <%= link_to("http://www.worldmachine.ie/", target: '_blank') do %>World Machine
  <% end %> home page.
</p>